### ISSUE TITLE
Issue with YAML literal braking highlighting in editor window

### ISSUE THREAD

**Issue by fandav73** [vermut/intellij-snakeyaml#13]
The following snippet comes from a Openstack Heat Template and the literal expression found in 
'resources.master_wc_notify.properties.config.str_replace.template' causes major problems to PyCharm.

```
resources:
  enable_etcd:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config: {get_file: fragments/enable-etcd.sh}

  master_wc_notify:
    type: "OS::Heat::SoftwareConfig"
    properties:
      group: ungrouped
      config:
        str_replace:
          template: |
            #!/bin/bash -v
            wc_notify --data-binary '{"status": "SUCCESS"}'
          params:
            wc_notify: {get_attr: [master_wait_handle, curl_cli]}

  swarm_master_init:
    type: "OS::Heat::MultipartMime"
    properties:
      parts:
        - config: {get_resource: disable_selinux}
        - config: {get_resource: write_heat_params}
        - config: {get_resource: disable_sshd_gss_auth}
        - config: {get_resource: configure_etcd}
        - config: {get_resource: configure_docker_storage}
        - config: {get_resource: enable_etcd}
        - config: {get_resource: master_wc_notify}

```

Highlighting in the editor windows gets broken and the IDE becomes very hard to use (try selecting lines below the problem...).
A complete template file can be found [here](https://github.com/openstack/magnum/blob/master/magnum/templates/kubernetes/kubemaster.yaml)

The single quotes in the wc_notify line are causing the issue, although this is valid yaml (code validated).
