### ISSUE TITLE
yaml folding blocks (with chomping and/or indentation indicators) incorrectly identified as errors

### ISSUE THREAD

**Issue by cognifloyd** [vermut/intellij-snakeyaml#23]
It seems that SnakeYAML is not identifying folding blocks correctly. The highlighter is highlighting random parts of the folded block when it should all be just text. And PyCharm is complaining about syntax errors when none are present.

This issue is very similar issue to #13. I installed the dev version of the plugin linked in that issue to see if it fixed it, and it does not seem to. All of the screenshots below are with that dev version in d16efef of the plugin installed.

My example, below, is in an ansible playbook (The screenshots show the Ansible/YAML plugin, but I get the same results whether I set `*.yml/*.yaml` to SnakeYAML directly or use the Ansible/YAML plugin which uses SnakeYAML).

This is a short snippet using a [folded block with indentation and chomping indicators](https://stackoverflow.com/a/21699210/1134951) (the: `>10-`)

```yaml
---
- hosts: all
  tasks:
    - name: "foo bar"
      lineinfile:
        path: /some/path/file
        line: >10-
            '{{ some_var }}': (
          {{ some_other_var}}
          {% if extras_var %}{% for e in extras_var %}, '{{ e }}'{% endfor %}{% endif %}
          ),
```

# Screenshots
Here are a few variations with screenshots:

## `>10-`
*note the extra two spaces before first line which yaml would include in the string*
![selection_015](https://user-images.githubusercontent.com/1558590/26893707-b70f8eae-4b81-11e7-90c0-334eb84406a6.png)

## `>-`
*extra spaces removed*
![selection_016](https://user-images.githubusercontent.com/1558590/26893722-c2ac1926-4b81-11e7-8691-c5054204f09d.png)

## `>`
*extra spaces removed*
![selection_017](https://user-images.githubusercontent.com/1558590/26893737-ce9ac8ea-4b81-11e7-86f4-9fc692c4f824.png)

## `>10`
*includes extra two spaces*
![selection_018](https://user-images.githubusercontent.com/1558590/26893753-da950d22-4b81-11e7-9533-04cbbfef5f07.png)

# Errors
* "Expected some indent after > or |" on the red underline on the `10` or the `-` of line 7.
* "Expected key-val pair or array item" on all of the rest of the red lines.
